package mcp

import (
	"context"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

type setRuleOutboundIn struct {
	Index    int    `json:"index" jsonschema:"rule position from list_singbox_rules"`
	Outbound string `json:"outbound" jsonschema:"target outbound tag from list_singbox_outbounds or list_singbox_tunnels"`
}

type rulesOut struct {
	Rules []SingboxRule `json:"rules" jsonschema:"in evaluation order — sing-box takes the FIRST rule that matches"`
	// HasDraft repeats the staging flag here because these rules come from
	// the draft when one exists: an agent reading them as live would
	// report a change that nobody has applied.
	HasDraft bool `json:"hasDraft" jsonschema:"true means these rules include staged, NOT YET APPLIED edits"`
}

type outboundsOut struct {
	Outbounds []SingboxOutbound `json:"outbounds"`
	HasDraft  bool              `json:"hasDraft" jsonschema:"true means the router holds changes that are not applied; the groups and members listed include them, and sing-box is not running them yet"`
}

type outboundDetailIn struct {
	Tag           string `json:"tag" jsonschema:"group tag from list_singbox_outbounds, or a subscription's groupTag"`
	MembersOffset int    `json:"membersOffset,omitempty" jsonschema:"index of the first member to return; default 0"`
}

// outboundDetailOut is the group with Members replaced by one page.
// MemberCount is always the real size, so a short page is never mistaken
// for a short group.
type outboundDetailOut struct {
	SingboxOutbound
	Members          []SingboxGroupMember `json:"members"`
	MembersOffset    int                  `json:"membersOffset" jsonschema:"index of the first member returned"`
	MembersTruncated bool                 `json:"membersTruncated" jsonschema:"true when members beyond this page remain — call again with a larger membersOffset before concluding a server is absent"`
	HasDraft         bool                 `json:"hasDraft" jsonschema:"true means the router holds changes that are not applied; the groups and members listed include them, and sing-box is not running them yet"`
}

// pageOutboundDetail cuts one page of members. An offset past the end
// yields an empty page rather than an error.
func pageOutboundDetail(detail SingboxOutboundDetail, offset int) outboundDetailOut {
	total := len(detail.Members)
	start := min(offset, total)
	end := min(start+MaxGroupMembersInOutput, total)
	page := detail.Members[start:end:end]
	if page == nil {
		page = []SingboxGroupMember{}
	}
	out := outboundDetailOut{SingboxOutbound: detail.SingboxOutbound, Members: page, MembersOffset: start, MembersTruncated: end < total, HasDraft: detail.HasDraft}
	out.MemberCount = total
	return out
}

type stagedOut struct {
	Staged bool `json:"staged" jsonschema:"always true: the change is in the draft and does NOT affect traffic until apply_singbox_staging"`
	Index  int  `json:"index"`
}

type applyOut struct {
	Applied bool `json:"applied"`
}

type discardOut struct {
	Discarded bool `json:"discarded"`
}

// stagedNotice is attached to every staging write so the model cannot
// report the change as live. Structured output alone is not enough: a
// model that skims tends to read "staged: true" as "done".
const stagedNotice = "The change is staged, not applied: traffic still follows the previous configuration. " +
	"Call apply_singbox_staging to publish it, or tell the user it is waiting in the web interface."

func registerRouterTools(s *mcp.Server, d Deps) {
	mcp.AddTool(s, &mcp.Tool{
		Name: "list_singbox_rules",
		Description: "Routing rules of the sing-box router, in evaluation order — sing-box uses the FIRST rule that matches, so position decides the outcome. " +
			"Rules marked managed are generated by awg-manager and rewritten on the next reconcile; editing one has no lasting effect. " +
			"These are separate from the NDMS domain lists in list_dns_routes.",
		Annotations: readOnly("List sing-box rules"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, rulesOut, error) {
		rules, hasDraft, err := d.ListSingboxRules(ctx)
		if rules == nil {
			rules = []SingboxRule{}
		}
		return nil, rulesOut{Rules: rules, HasDraft: hasDraft}, err
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "list_singbox_outbounds",
		Description: "Groups of servers in sing-box — selectors and urltest groups — that a rule can point at, with the member each one is routing through now. " +
			"Subscriptions appear here as groups (subscriptionId set); so do groups that gather several subscriptions (aggregateOf set). " +
			"runtimeKnown=false means sing-box gave no answer for that group: it exists, and nothing is known about what it is doing. " +
			"outOfSync=true means sing-box answered and is not running the group as listed — because of a draft not applied yet (hasDraft says whether there is one), the sing-box router being switched off, or a reload in progress. " +
			"For the members of one group, call get_singbox_outbound. A rule may also target a single proxy from list_singbox_tunnels, or the built-in direct and block.",
		Annotations: readOnly("List sing-box outbounds"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, outboundsOut, error) {
		list, hasDraft, err := d.ListSingboxOutbounds(ctx)
		if list == nil {
			list = []SingboxOutbound{}
		}
		return nil, outboundsOut{Outbounds: list, HasDraft: hasDraft}, err
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "get_singbox_outbound",
		Description: "One sing-box group in full: its members, which one carries traffic now, and the last delay the engine recorded for each. Use it to answer which server a subscription or group is using. " +
			"Members are paged: when membersTruncated is true, call again with membersOffset. " +
			"Read lastDelayMs here before probing — singbox_delay_check makes a real request through the server, and a subscription can hold hundreds. " +
			"delayKnown=false means no test is on record, not that the server is down; runtimeKnown=false means sing-box gave no answer for this group and nothing here describes the present. " +
			"outOfSync=true means sing-box is not running the group as listed — a draft not applied yet (see hasDraft), the sing-box router switched off, or a reload in progress; activeMember then describes what is running and may not be among the members.",
		Annotations: readOnly("Get sing-box group"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, in outboundDetailIn) (*mcp.CallToolResult, outboundDetailOut, error) {
		tag, err := requireSingboxTag(in.Tag, "list_singbox_outbounds")
		if err != nil {
			return nil, outboundDetailOut{}, err
		}
		if in.MembersOffset < 0 {
			return nil, outboundDetailOut{}, fmt.Errorf("membersOffset must not be negative")
		}
		detail, err := d.GetSingboxOutbound(ctx, tag)
		if err != nil {
			return nil, outboundDetailOut{}, err
		}
		return nil, pageOutboundDetail(detail, in.MembersOffset), nil
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "get_singbox_staging",
		Description: "Whether the sing-box router has unapplied changes waiting, and when they were drafted. " +
			"A draft may hold edits made in the web interface as well as through MCP — they share one draft.",
		Annotations: readOnly("Sing-box staging status"),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, SingboxStaging, error) {
		out, err := d.SingboxStaging(ctx)
		return nil, out, err
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "set_singbox_rule_outbound",
		Description: "Send one routing rule's traffic through a different outbound. The edit goes into the router's DRAFT and changes nothing until apply_singbox_staging runs. " +
			"Rules generated by awg-manager cannot be edited this way.",
		Annotations: safeWrite("Set rule outbound", true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, in setRuleOutboundIn) (*mcp.CallToolResult, stagedOut, error) {
		if in.Index < 0 {
			return nil, stagedOut{}, fmt.Errorf("index must not be negative (use list_singbox_rules)")
		}
		if strings.TrimSpace(in.Outbound) == "" {
			return nil, stagedOut{}, fmt.Errorf("outbound is required (use list_singbox_outbounds)")
		}
		if err := d.SetSingboxRuleOutbound(ctx, in.Index, strings.TrimSpace(in.Outbound)); err != nil {
			return nil, stagedOut{}, err
		}
		return &mcp.CallToolResult{Content: []mcp.Content{&mcp.TextContent{Text: stagedNotice}}},
			stagedOut{Staged: true, Index: in.Index}, nil
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "apply_singbox_staging",
		Description: "Publish the sing-box router's draft: validate it and reload the engine. " +
			"WARNING: this applies the WHOLE draft, including any edits the user started in the web interface and has not finished. " +
			"Check get_singbox_staging first and confirm with the user when the draft is not only yours.",
		Annotations: safeWrite("Apply sing-box draft", false),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, applyOut, error) {
		if err := d.ApplySingboxStaging(ctx); err != nil {
			return nil, applyOut{}, err
		}
		return nil, applyOut{Applied: true}, nil
	})

	mcp.AddTool(s, &mcp.Tool{
		Name: "discard_singbox_staging",
		Description: "Throw away the sing-box router's draft and return to the applied configuration. " +
			"DESTRUCTIVE: the draft is shared, so this also destroys unfinished edits the user made in the web interface, and they cannot be recovered. " +
			"Confirm with the user before calling it.",
		Annotations: destructiveWrite("Discard sing-box draft", true),
	}, func(ctx context.Context, _ *mcp.CallToolRequest, _ empty) (*mcp.CallToolResult, discardOut, error) {
		if err := d.DiscardSingboxStaging(ctx); err != nil {
			return nil, discardOut{}, err
		}
		return nil, discardOut{Discarded: true}, nil
	})
}
