// Code generated by scripts/regen-embedded.sh (из релиза форка hoaxisr/amnezia-box); DO NOT EDIT.
package installer

const RequiredVersion = "1.15.0-alpha.4-awgm.18"

// RequiredTags — теги сборки pinned-бинаря (строка `Tags:` из `sing-box version`),
// сняты с mipsel-ассета. Гейт-значимые теги (with_naive_outbound) одинаковы
// для всех трёх архитектур; служебные (with_low_memory, with_musl) могут
// отличаться — это только отображение в Status.Features.
// Обновляется regen-embedded.sh под qemu-user; без qemu — руками при бампе.
var RequiredTags = []string{"with_gvisor", "with_quic", "with_wireguard", "with_utls", "with_acme", "with_clash_api", "with_v2ray_api", "with_naive_outbound", "with_cloudflared", "badlinkname", "tfogo_checklinkname0", "with_musl", "with_awg", "with_low_memory"}

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.4-awgm.18/singbox-1.15.0-alpha.4-awgm.18-mipsel-3.4", SHA256: "88856254ebe0841e06adad2ebd870d50c728f98676bf2c0098422de109a578fa", Size: 75407152},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.4-awgm.18/singbox-1.15.0-alpha.4-awgm.18-mips-3.4", SHA256: "611ddb4e47abf06ea2c33826971184e725359e44647d45f8a83a495929506323", Size: 57933981},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.4-awgm.18/singbox-1.15.0-alpha.4-awgm.18-aarch64-3.10", SHA256: "2d622fcc5edf66c5c18a3ce56eb2476cfc40e295a733c0f0d9d0e4f7c3005572", Size: 62393944},
}
