// Code generated by scripts/regen-embedded.sh (из релиза форка hoaxisr/amnezia-box); DO NOT EDIT.
package installer

const RequiredVersion = "1.15.0-alpha.8-awgm.27"

// RequiredTags — теги сборки pinned-бинаря (строка `Tags:` из `sing-box version`),
// сняты с mipsel-ассета. Гейт-значимые теги (with_naive_outbound) одинаковы
// для всех трёх архитектур; служебные (with_low_memory, with_musl) могут
// отличаться — это только отображение в Status.Features.
// Обновляется regen-embedded.sh под qemu-user; без qemu — руками при бампе.
var RequiredTags = []string{"with_quic", "with_wireguard", "with_utls", "with_acme", "with_clash_api", "with_v2ray_api", "with_naive_outbound", "with_cloudflared", "badlinkname", "tfogo_checklinkname0", "with_musl", "with_awg", "with_low_memory", "with_trusttunnel"}

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.8-awgm.27/singbox-1.15.0-alpha.8-awgm.27-mipsel-3.4", SHA256: "0db3b3259ef1ce3b78c7411a305f9e465aa584aa013c075edf8739ef7fff732e", Size: 69817732},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.8-awgm.27/singbox-1.15.0-alpha.8-awgm.27-mips-3.4", SHA256: "46329d6bbc3ce98334ebfff3257b0368d6101f58249ee5fa57ae2992e241a621", Size: 52363421},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.8-awgm.27/singbox-1.15.0-alpha.8-awgm.27-aarch64-3.10", SHA256: "efc7f63337ca5d37e36def2d1b811c082f69c8e5d88092823d6b22f164e89d9a", Size: 57083672},
}
