// Code generated by scripts/regen-embedded.sh (из релиза форка hoaxisr/amnezia-box); DO NOT EDIT.
package installer

const RequiredVersion = "1.15.0-alpha.6-awgm.24"

// RequiredTags — теги сборки pinned-бинаря (строка `Tags:` из `sing-box version`),
// сняты с mipsel-ассета. Гейт-значимые теги (with_naive_outbound) одинаковы
// для всех трёх архитектур; служебные (with_low_memory, with_musl) могут
// отличаться — это только отображение в Status.Features.
// Обновляется regen-embedded.sh под qemu-user; без qemu — руками при бампе.
var RequiredTags = []string{"with_quic", "with_wireguard", "with_utls", "with_acme", "with_clash_api", "with_v2ray_api", "with_naive_outbound", "with_cloudflared", "badlinkname", "tfogo_checklinkname0", "with_musl", "with_awg", "with_low_memory", "with_trusttunnel"}

var EmbeddedBinaries = map[string]BinarySpec{
	"mipsel-3.4":   {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.6-awgm.24/singbox-1.15.0-alpha.6-awgm.24-mipsel-3.4", SHA256: "6cf4e19db7b0dff74a3eb8fa9f5b0bc0d582fa90a55dd0f5dbd06ea203402cd8", Size: 69061600},
	"mips-3.4":     {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.6-awgm.24/singbox-1.15.0-alpha.6-awgm.24-mips-3.4", SHA256: "29406cc7b7922bed583b0617772a847c8ba463e4639f66bc05c92efefc3b6613", Size: 51642525},
	"aarch64-3.10": {Version: RequiredVersion, URL: "http://repo.hoaxisr.ru/singbox/1.15.0-alpha.6-awgm.24/singbox-1.15.0-alpha.6-awgm.24-aarch64-3.10", SHA256: "ddc0de72d4d903589a7cbe1fddf4a40d44f3937a201fdd18427a640d4c62d95b", Size: 56440984},
}
